font_size: 13
theme: pywal
tree_1:
  general:
    github: "https://github.com/TechnicalDC"
    gmail: "https://mail.google.com/"
    localhost: "http://127.0.0.1:8000"
    technicaldc: "https://technicaldc.github.io"
  reddit:
    frontpage: 
      - "https://www.reddit.com/"
      - "front page"
    unixporn: "https://www.reddit.com/r/unixporn/"
tree_2:
  youtube:
    homepage: "https://www.youtube.com/"
    distrotube: "https://www.youtube.com/c/DistroTube"
    bugswriter: "https://www.youtube.com/@bugswriter_"
    lukesmith:
      - "https://www.youtube.com/c/LukeSmithxyz"
      - "luke smith"
    thelinuxcast:
      - "https://www.youtube.com/c/TheLinuxCast"
      - "the linux cast"
    thelinuxexperiment:
      - "https://www.youtube.com/c/TheLinuxExperiment"
      - "the linux experiment"
    studio:
      - "https://studio.youtube.com/channel/UCh98peCVtmezFdSR18kipcg"
      - "youtube studio"
tree_3:
  docs:
    qtile: "http://docs.qtile.org/en/stable/"
  other:
    savefrom: "https://en.savefrom.net/151/"
    nerdfont: "https://www.nerdfonts.com/cheat-sheet"
    braille-art: "https://lachlanarthur.github.io/Braille-ASCII-Art"
